// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: process_handler/process_handler.proto

package process

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_process_handler_process_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_handler_process_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_process_handler_process_handler_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_process_handler_process_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_handler_process_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_process_handler_process_handler_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_process_handler_process_handler_proto protoreflect.FileDescriptor

const file_process_handler_process_handler_proto_rawDesc = "" +
	"\n" +
	"%process_handler/process_handler.proto\x12\ahandler\"*\n" +
	"\x0eProcessRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x0fProcessResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2P\n" +
	"\x0fValidateHandler\x12=\n" +
	"\x06Handle\x12\x17.handler.ProcessRequest\x1a\x18.handler.ProcessResponse\"\x00B\x1cZ\x1amaxfuls.process.v1;processb\x06proto3"

var (
	file_process_handler_process_handler_proto_rawDescOnce sync.Once
	file_process_handler_process_handler_proto_rawDescData []byte
)

func file_process_handler_process_handler_proto_rawDescGZIP() []byte {
	file_process_handler_process_handler_proto_rawDescOnce.Do(func() {
		file_process_handler_process_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_process_handler_process_handler_proto_rawDesc), len(file_process_handler_process_handler_proto_rawDesc)))
	})
	return file_process_handler_process_handler_proto_rawDescData
}

var file_process_handler_process_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_process_handler_process_handler_proto_goTypes = []any{
	(*ProcessRequest)(nil),  // 0: handler.ProcessRequest
	(*ProcessResponse)(nil), // 1: handler.ProcessResponse
}
var file_process_handler_process_handler_proto_depIdxs = []int32{
	0, // 0: handler.ValidateHandler.Handle:input_type -> handler.ProcessRequest
	1, // 1: handler.ValidateHandler.Handle:output_type -> handler.ProcessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_process_handler_process_handler_proto_init() }
func file_process_handler_process_handler_proto_init() {
	if File_process_handler_process_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_process_handler_process_handler_proto_rawDesc), len(file_process_handler_process_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_process_handler_process_handler_proto_goTypes,
		DependencyIndexes: file_process_handler_process_handler_proto_depIdxs,
		MessageInfos:      file_process_handler_process_handler_proto_msgTypes,
	}.Build()
	File_process_handler_process_handler_proto = out.File
	file_process_handler_process_handler_proto_goTypes = nil
	file_process_handler_process_handler_proto_depIdxs = nil
}
